suricata:
  image: jasonish/suricata:beta
  volumes:
    - /var/log/suricata
  privileged: true
  net: host

  # To pass in the interface and other arguments.
  command: -i eth0 -k none

elasticsearch:
  image: elasticsearch:latest
  command: --network.host 0.0.0.0
  # volumes:
  #   - ./data/elasticsearch:/usr/share/elasticsearch/data

logstash:
  image: logstash:latest
  volumes:
    - ./config:/config
  volumes_from:
    - suricata
  links:
    - elasticsearch
  command: -f /config/logstash.conf

kibana:
  image: kibana:latest
  ports:
    - 5601:5601
  links:
    - elasticsearch

evebox:
  image: jasonish/evebox
  ports:
    - 5636:5636
  links:
    - elasticsearch
